name: $(date:yyyyMMdd)$(rev:.rr) #20200319.00

pr:
  - master

stages:
  - stage:
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build
            workingDirectory: $(working_dir)

  - stage: test
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test --collect:"XPlat Code Coverage"
            workingDirectory: $(working_dir)
  
  - stage: analyze
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: DotnetGlobalToolInstaller@0
            inputs:
              name: "dotnet-sonarscanner"
          - script: |
              dotnet sonarscanner begin /k:"Christian-Bennett_p1-Christian-Bennett" /o:"Christian-Bennett" /d:sonar.login="$SONAR_LOGIN" /d:sonar.host.url=https://sonarcloud.io
              dotnet build
              dotnet test --collect:"XPlat Code Coverage"
              dotnet sonarscanner end /d:sonar.login="SONAR_LOGIN"
            workingDirectory: $(working_dir)
            env:
              SONAR_LOGIN: $(sonar_login)

  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu18.04
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "docker"
              command: "login"
          - script: |
              docker image build --file dockerfile --tag bennetcd/p1 .
              docker image push bennetcd/p1
            workingDirectory: $(working_dir)
            env:
              DOCKER_IMAGE: $(image_name)
          - task:
            inputs:
              containerRegistry: "docker"
              command: "logout"

  - stage: deploy
    jobs:
      jobs:
        - job:
          pool:
            vmImage: ubuntu-18.04
          steps:
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: "AzureRM"
                azureSubscription: "Azure subscription 1(a4086594-e733-4902-b070-4e28fa022181)"
                appType: "webAppContainer"
                WebAppName: "PizzaBox"
                DockerNamespace: "bennetcd"
                DockerRepository: "p1"      

trigger:
  - master

variables:
  - name: image_name
    value: bennetcd/p1
  - name: working_dir
    value: $(System.DefaultWorkingDirectory)/PizzaBox